AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  DestinationLambdaARN:
    Type: String
    MinLength: 3
    ConstraintDescription: 'Required. You need to specify an existing Lambda ARN which you want to invoke with this API'
Resources:
  AttachableApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          /create:
            post:
              responses: {}
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DestinationLambdaARN}/invocations
  ApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref DestinationLambdaARN
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AttachableApi}/*/POST/create
Outputs:
  ApiUrl:
    Value: !Sub https://${AttachableApi}.execute-api.${AWS::Region}.amazonaws.com/prod/create
    Description: The URL of the API Gateway you invoke